[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "paris"
remappings = [
    "@chainlink/local/=lib/chainlink-local/",
    "@chainlink/contracts-ccip/=lib/chainlink-local/lib/chainlink-ccip/chains/evm/",
    "@chainlink/contracts/=lib/chainlink-local/lib/chainlink-evm/contracts/",
    "@openzeppelin/contracts@4.8.3/=lib/chainlink-local/src/vendor/openzeppelin-solidity/v4.8.3/contracts/",
    "@openzeppelin/contracts@5.0.2/=lib/chainlink-local/src/vendor/openzeppelin-solidity/v5.0.2/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum-sepolia = "${ARB_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
